### ISSUE TITLE
VSIX installer complains extension not compatible with VS2017

### ISSUE THREAD

**Issue by jeremymeng** [jasonmalinowski/roslyn-info-logger#2]
![image](https://user-images.githubusercontent.com/7583839/37367564-f9d470ea-26c0-11e8-867d-b563ce17a01b.png)

**Comment by jasonmalinowski** [comment]
This extension has been migrated into the [Project System Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools) and that fully supports 2017 and 2019.
